### PR TITLE
Update to camel 2.22 + Fix test and compile errors

### PR DESCRIPTION
**Pull request by ddoaj97**
I've noticed that the camel-extra project is lagging behind the Camel core project. The latest camel-extra release is aligned with Camel 2.18.0 whereas the camel-core project is already at 2.22.0.

Some of the components in extra no longer work with Camel 2.22.0 due to breaking changes in the Camel API's. For example, the JCIFS component no longer works due to changes in the GenericFileConsumer class. I get the following stack trace when trying to use it:
```
Caused by: java.lang.NoSuchMethodError: org.apache.camel.component.file.GenericFileConsumer.<init>(Lorg/apache/camel/component/file/GenericFileEndpoint;Lorg/apache/camel/Processor;Lorg/apache/camel/component/file/GenericFileOperations;)V
    at org.apacheextras.camel.component.jcifs.SmbConsumer.<init> (SmbConsumer.java:45)
    at org.apacheextras.camel.component.jcifs.SmbEndpoint.createConsumer (SmbEndpoint.java:51)
    at org.apacheextras.camel.component.jcifs.SmbEndpoint.createConsumer (SmbEndpoint.java:34)
```

On the camel-extra mailing list someone has reported the same problem here: http://camel-extra.1091541.n5.nabble.com/Camel-JCIFS-Component-not-working-with-camel-core-2-22-0-td512.html

This pull request updates the Camel dependencies to version 2.22.0 and fixes all compilation and test errors (see commit message for more details).

From the Camel mailing list I had gathered that the project was no longer being released due to failing integration tests in the Apache Karaf container. I also had a look at those and all tests are green now when running `mvn clean install -Pintegration`.

Could someone review my changes, merge this pull request and provision a new release?

### CODE REVIEW

**Comment by ullgren** [comment]
Thanks for the contribution.
Will try to get time to cut a new release ASAP.
